apiVersion: v1
kind: Pod
metadata:
  name: rest-api-feed
spec:
  containers:
    - image: cliffordbernard/rest-api-feed
      name: feed
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
  restartPolicy: Always
